import type { SupplierProduct } from "./import-goods.types"

export const mockSupplierProducts: SupplierProduct[] = [
    {
        maSanPham: "SP001",
        tenSanPham: "Cà chua cherry",
        donVi: "kg",
        giaBan: 25000,
        soLuongTon: 150,
        trangThai: "active",
        hinhAnh: "/cherry-tomatoes.jpg",
        moTa: "Cà chua cherry tươi ngon, giàu vitamin C",
        xuatXu: "Đà Lạt",
        hanSuDung: "2024-12-31",
    },
    {
        maSanPham: "SP002",
        tenSanPham: "Rau cải xanh",
        donVi: "kg",
        giaBan: 15000,
        soLuongTon: 200,
        trangThai: "active",
        hinhAnh: "/fresh-green-vegetables.jpg",
        moTa: "Rau cải xanh tươi, không thuốc trừ sâu",
        xuatXu: "Lâm Đồng",
        hanSuDung: "2024-12-25",
    },
    {
        maSanPham: "SP003",
        tenSanPham: "Củ cà rót",
        donVi: "kg",
        giaBan: 18000,
        soLuongTon: 100,
        trangThai: "active",
        hinhAnh: "/fresh-cucumber.png",
        moTa: "Củ cà rót tươi giòn, thích hợp làm salad",
        xuatXu: "Tiền Giang",
        hanSuDung: "2024-12-28",
    },
    {
        maSanPham: "SP004",
        tenSanPham: "Thịt ba chỉ heo",
        donVi: "kg",
        giaBan: 180000,
        soLuongTon: 50,
        trangThai: "active",
        hinhAnh: "/pork-belly-meat.jpg",
        moTa: "Thịt ba chỉ heo tươi, đảm bảo vệ sinh an toàn thực phẩm",
        xuatXu: "Đồng Nai",
        hanSuDung: "2024-12-20",
    },
    {
        maSanPham: "SP005",
        tenSanPham: "Cá thu tươi",
        donVi: "kg",
        giaBan: 120000,
        soLuongTon: 30,
        trangThai: "active",
        hinhAnh: "/fresh-mackerel-fish.jpg",
        moTa: "Cá thu tươi ngon, giàu omega-3",
        xuatXu: "Vũng Tàu",
        hanSuDung: "2024-12-18",
    },
]


